# Custom Language File for Launcher Customizer

[ejs.app]
title = "DONG Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "이동욱입니다"
welcomeDescription = "누구세용?"
welcomeDescCTA = "거기 짜장면 집이죵? 어 아뉘넹"
